#!/bin/bash

#docker run --privileged --rm -it -v $PWD:/workdir archiso-builder sudo mkarchiso -v -w workdir/ -o out/ .


### Using Server i9
#docker run --privileged -it -v $(pwd):/workdir archiso-builder /bin/bash
#mkarchiso -v -w workdir/ -o out/ .
